name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go toolchain
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # or your project's Go version

      # Step 3: Build the app
      - name: Build production binary
        run: scripts/buildprod.sh
